// packages/party/content/5-form-input/4-select/vue/ColorSelect.vue
<template>
  <select @change="selectedColorId = $event.target.value" :value="selectedColorId">
    <template :key="index" v-for="(color, index) in colors">
      <option :value="color.id" :disabled="color.isDisabled">
        {{ color.text }}
      </option>
    </template>
  </select>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const selectedColorId = ref(2);
const colors = ref([
  { id: 1, text: 'red' },
  { id: 2, text: 'blue' },
  { id: 3, text: 'green' },
  { id: 4, text: 'gray', isDisabled: true },
]);
</script>

// packages/party/content/5-form-input/4-select/react/ColorSelect.tsx
import * as React from 'react';
import { useState } from 'react';

export default function ColorSelect(props: any) {
  const [selectedColorId, setSelectedColorId] = useState(() => 2);

  const [colors, setColors] = useState(() => [
    {
      id: 1,
      text: 'red',
    },
    {
      id: 2,
      text: 'blue',
    },
    {
      id: 3,
      text: 'green',
    },
    {
      id: 4,
      text: 'gray',
      isDisabled: true,
    },
  ]);

  return (
    <select onChange={(event) => setSelectedColorId(event.target.value)} value={selectedColorId}>
      {colors?.map((color) => (
        <option value={color.id} disabled={color.isDisabled}>
          {color.text}
        </option>
      ))}
    </select>
  );
}
