// packages/party/content/2-templating/4-event-click/angular/Counter.ts
import { Component } from '@angular/core';

@Component({
  selector: 'counter, Counter',
  template: `
    <div>
      <p>Counter: {{ count }}</p>
      <button (click)="(incrementCount)">+1</button>
    </div>
  `,
})
export default class Counter {
  count = 0;
  incrementCount = function incrementCount() {
    this.count = this.count + 1;
  };
}

// packages/party/content/2-templating/4-event-click/react/Counter.tsx
import * as React from "react";
import { useState } from "react";

export default function Counter(props: any) {
  const [count, setCount] = useState(() => 0);

  function incrementCount() {
    setCount(count + 1);
  }

  return (
    <>
      <p>
        Counter:
        {count}
      </p>
      <button onClick={() => incrementCount}>+1</button>
    </>
  );
}
