// packages/party/content/2-templating/6-conditional/react/TrafficLight.tsx
import * as React from 'react';
import { useState } from 'react';

export default function TrafficLight(props: any) {
  const [TRAFFIC_LIGHTS, setTRAFFIC_LIGHTS] = useState(() => ['red', 'green']);

  const [lightIndex, setLightIndex] = useState(() => 0);

  function light() {
    return TRAFFIC_LIGHTS[lightIndex];
  }

  function toggleLight() {
    setLightIndex(lightIndex === 0 ? 1 : 0);
  }

  return (
    <>
      <button onClick={(event) => toggleLight}>Toggle light</button>
      <p>
        Light is:
        {light()}
      </p>
      <p>
        You must
        {light() === 'red' ? <span>STOP</span> : <span>GO</span>}
      </p>
    </>
  );
}

// packages/party/content/2-templating/6-conditional/solid/TrafficLight.jsx
import { Show, createSignal } from 'solid-js';
function TrafficLight(props) {
	const [TRAFFIC_LIGHTS, setTRAFFIC_LIGHTS] = createSignal(['red', 'green']);
	const [lightIndex, setLightIndex] = createSignal(0);
	function light() {
		return TRAFFIC_LIGHTS()[lightIndex()];
	}
	function toggleLight() {
		setLightIndex(lightIndex() === 0 ? 1 : 0);
	}
	return (
		<>
			<button onClick={(event) => toggleLight}>Toggle light</button>
			<p>
				Light is:
				{light()}
			</p>
			<p>
				You must
				<Show fallback={<span>GO</span>} when={light() === 'red'}>
					<span>STOP</span>
				</Show>
			</p>
		</>
	);
}
export default TrafficLight;
