// packages/party/content/4-component-composition/2-emit-to-parent/angular/App.ts
import { Component } from '@angular/core';

import AnswerButton from './AnswerButton.svelte';

@Component({
  selector: 'app, App',
  template: `
    <div>
      <p>Can I come ?</p>
      <answer-button (yes)="(onAnswerYes)" (no)="(onAnswerNo)"></answer-button>
      <p style="font-size: 50px">{{ canCome ? '😀' : '😥' }}</p>
    </div>
  `,
})
export default class App {
  canCome = true;
  onAnswerNo = function onAnswerNo() {
    this.canCome = false;
  };
  onAnswerYes = function onAnswerYes() {
    this.canCome = true;
  };
}

// packages/party/content/4-component-composition/2-emit-to-parent/vue/App.vue
<template>
  <p>Can I come ?</p>
  <answer-button @yes="onAnswerYes" @no="onAnswerNo"></answer-button>
  <p style="font-size: 50px">{{ canCome ? '😀' : '😥' }}</p>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import AnswerButton from './AnswerButton.svelte';

const canCome = ref(true);

function onAnswerNo() {
  canCome.value = false;
}
function onAnswerYes() {
  canCome.value = true;
}
</script>
