// packages/party/content/5-form-input/5-bind-group/qwik/BindGroup.jsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";
export const BindGroup = component$((props) => {
  const state = useStore({ fillings: [], tortilla: "Plain" });
  return (
    <div>
      <input
        type="radio"
        value="Plain"
        checked={(() => {
          state.tortilla === "Plain";
        })()}
        onChange$={(event) => (state.tortilla = event.target.value)}
      ></input>
      <input
        type="radio"
        value="Whole wheat"
        checked={(() => {
          state.tortilla === "Whole wheat";
        })()}
        onChange$={(event) => (state.tortilla = event.target.value)}
      ></input>
      <input
        type="radio"
        value="Spinach"
        checked={(() => {
          state.tortilla === "Spinach";
        })()}
        onChange$={(event) => (state.tortilla = event.target.value)}
      ></input>
      <br></br>
      <br></br>
      <input
        type="checkbox"
        value="Rice"
        checked={state.fillings.includes("Rice")}
        onChange$={(event) =>
          event.target.checked
            ? state.fillings.push(event.target.value)
            : state.fillings.splice(state.fillings.indexOf("Rice"), 1)
        }
      ></input>
      <input
        type="checkbox"
        value="Beans"
        checked={state.fillings.includes("Beans")}
        onChange$={(event) =>
          event.target.checked
            ? state.fillings.push(event.target.value)
            : state.fillings.splice(state.fillings.indexOf("Beans"), 1)
        }
      ></input>
      <input
        type="checkbox"
        value="Cheese"
        checked={state.fillings.includes("Cheese")}
        onChange$={(event) =>
          event.target.checked
            ? state.fillings.push(event.target.value)
            : state.fillings.splice(state.fillings.indexOf("Cheese"), 1)
        }
      ></input>
      <input
        type="checkbox"
        value="Guac (extra)"
        checked={state.fillings.includes("Guac (extra)")}
        onChange$={(event) =>
          event.target.checked
            ? state.fillings.push(event.target.value)
            : state.fillings.splice(state.fillings.indexOf("Guac (extra)"), 1)
        }
      ></input>
      <p>Tortilla: {state.tortilla}</p>
      <p>Fillings: {state.fillings}</p>
    </div>
  );
});
export default BindGroup;

// packages/party/content/5-form-input/5-bind-group/react/BindGroup.tsx
import * as React from "react";
import { useState } from "react";

export default function BindGroup(props: any) {
  const [tortilla, setTortilla] = useState(() => "Plain");

  const [fillings, setFillings] = useState(() => []);

  return (
    <div>
      <input
        type="radio"
        value="Plain"
        checked={tortilla === "Plain"}
        onChange={(event) => setTortilla(event.target.value)}
      />
      <input
        type="radio"
        value="Whole wheat"
        checked={tortilla === "Whole wheat"}
        onChange={(event) => setTortilla(event.target.value)}
      />
      <input
        type="radio"
        value="Spinach"
        checked={tortilla === "Spinach"}
        onChange={(event) => setTortilla(event.target.value)}
      />
      <br />
      <br />
      <input
        type="checkbox"
        value="Rice"
        checked={fillings.includes("Rice")}
        onChange={(event) =>
          event.target.checked
            ? fillings.push(event.target.value)
            : fillings.splice(fillings.indexOf("Rice"), 1)
        }
      />
      <input
        type="checkbox"
        value="Beans"
        checked={fillings.includes("Beans")}
        onChange={(event) =>
          event.target.checked
            ? fillings.push(event.target.value)
            : fillings.splice(fillings.indexOf("Beans"), 1)
        }
      />
      <input
        type="checkbox"
        value="Cheese"
        checked={fillings.includes("Cheese")}
        onChange={(event) =>
          event.target.checked
            ? fillings.push(event.target.value)
            : fillings.splice(fillings.indexOf("Cheese"), 1)
        }
      />
      <input
        type="checkbox"
        value="Guac (extra)"
        checked={fillings.includes("Guac (extra)")}
        onChange={(event) =>
          event.target.checked
            ? fillings.push(event.target.value)
            : fillings.splice(fillings.indexOf("Guac (extra)"), 1)
        }
      />
      <p>
        Tortilla:
        {tortilla}
      </p>
      <p>
        Fillings:
        {fillings}
      </p>
    </div>
  );
}
