// packages/party/content/4-component-composition/1-props/qwik/App.jsx
import UserProfile from './UserProfile.svelte';
import { Fragment, component$, h } from '@builder.io/qwik';
export const App = component$((props) => {
  return (
    <UserProfile
      name="John"
      age={20}
      favouriteColors={['green', 'blue', 'red']}
      isAvailable={true}
    ></UserProfile>
  );
});
export default App;

// packages/party/content/4-component-composition/1-props/angular/App.ts
import { Component } from '@angular/core';

import UserProfile from './UserProfile.svelte';

@Component({
  selector: 'app, App',
  template: `
    <user-profile
      name="John"
      [age]="20"
      [favouriteColors]="['green', 'blue', 'red']"
      [isAvailable]="true"
    ></user-profile>
  `,
})
export default class App {}
