// packages/party/content/4-component-composition/1-props/react/UserProfile.tsx
import * as React from "react";

export default function UserProfile(props: any) {
  return (
    <>
      <p>
        My name is
        {props.name}!
      </p>
      <p>
        My age is
        {props.age}!
      </p>
      <p>
        My favourite colors are
        {props.favouriteColors.join(", ")}!
      </p>
      <p>
        I am
        {props.isAvailable ? "available" : "not available"}
      </p>
    </>
  );
}

UserProfile.defaultProps = {};

// packages/party/content/4-component-composition/1-props/angular/UserProfile.ts
import { Component, Input } from '@angular/core';

const defaultProps = {};

@Component({
  selector: 'user-profile, UserProfile',
  template: `
    <div>
      <p>My name is {{ name }} !</p>
      <p>My age is {{ age }} !</p>
      <p>My favourite colors are {{ favouriteColors.join(', ') }} !</p>
      <p>I am {{ isAvailable ? 'available' : 'not available' }}</p>
    </div>
  `,
})
export default class UserProfile {
  @Input() name: any;
  @Input() age: any;
  @Input() favouriteColors: any;
  @Input() isAvailable: any;
}
