// packages/party/content/4-component-composition/4-context/react/Context.tsx
import * as React from 'react';
import { useState, useContext } from 'react';

export default function Context(props: any) {
  const [activeTab, setActiveTab] = useState(() => 0);

  const disabled = useContext('disabled');

  return (
    <Context.Provider value={activeTab}>
      <div>
        Is disabled?
        {disabled}
      </div>
    </Context.Provider>
  );
}

// packages/party/content/4-component-composition/4-context/qwik/Context.jsx
import {
  Fragment,
  component$,
  h,
  useContext,
  useContextProvider,
  useStore,
} from "@builder.io/qwik";
export const Context = component$((props) => {
  const disabled = useContext("disabled");
  const state = useStore({ activeTab: 0 });
  useContextProvider("activeTab", useStore({}));
  return <div>Is disabled? {disabled}</div>;
});
export default Context;
