// packages/party/content/4-component-composition/2-emit-to-parent/qwik/AnswerButton.jsx
import { Fragment, component$, h } from '@builder.io/qwik';
export const clickYes = function clickYes(props, state) {
  props.onYes();
};
export const clickNo = function clickNo(props, state) {
  props.onNo();
};
export const AnswerButton = component$((props) => {
  const state = {};
  return (
    <Fragment>
      <button onClick$={(event) => state.clickYes}> YES </button>
      <button onClick$={(event) => state.clickNo}> NO </button>
    </Fragment>
  );
});
export default AnswerButton;

// packages/party/content/4-component-composition/2-emit-to-parent/react/AnswerButton.tsx
import * as React from 'react';

export default function AnswerButton(props: any) {
	function clickYes() {
		props.onYes();
	}

	function clickNo() {
		props.onNo();
	}

	return (
		<>
			<button onClick={(event) => clickYes}> YES </button>
			<button onClick={(event) => clickNo}> NO </button>
		</>
	);
}
