// packages/party/content/4-component-composition/2-emit-to-parent/qwik/App.jsx
import AnswerButton from "./AnswerButton.svelte";
import { Fragment, component$, h, useStore } from "@builder.io/qwik";
export const App = component$((props) => {
  const state = useStore({
    canCome: true,
    onAnswerNo: "function onAnswerNo() {\n  state.canCome = false;\n}",
    onAnswerYes: "function onAnswerYes() {\n  state.canCome = true;\n}",
  });
  return (
    <Fragment>
      <p>Can I come ?</p>
      <AnswerButton
        onYes$={(event) => state.onAnswerYes}
        onNo$={(event) => state.onAnswerNo}
      ></AnswerButton>
      <p style="font-size: 50px;">{state.canCome ? "😀" : "😥"}</p>
    </Fragment>
  );
});
export default App;

// packages/party/content/4-component-composition/2-emit-to-parent/react/App.tsx
import * as React from 'react';
import { useState } from 'react';
import AnswerButton from './AnswerButton.svelte';

export default function App(props: any) {
  const [canCome, setCanCome] = useState(() => true);

  function onAnswerNo() {
    setCanCome(false);
  }

  function onAnswerYes() {
    setCanCome(true);
  }

  return (
    <>
      <p>Can I come ?</p>
      <AnswerButton onYes={(event) => onAnswerYes} onNo={(event) => onAnswerNo} />
      <p style="font-size: 50px;">{canCome ? '😀' : '😥'}</p>
    </>
  );
}
