// packages/party/content/2-templating/4-event-click/react/Counter.tsx
import * as React from 'react';
import { useState } from 'react';

export default function Counter(props: any) {
  const [count, setCount] = useState(() => 0);

  function incrementCount() {
    setCount(count + 1);
  }

  return (
    <>
      <p>
        Counter:
        {count}
      </p>
      <button onClick={(event) => incrementCount(event)}>+1</button>
    </>
  );
}

// packages/party/content/2-templating/4-event-click/qwik/Counter.jsx
import { Fragment, component$, h, useStore } from '@builder.io/qwik';
export const incrementCount = function incrementCount(props, state) {
  state.count = state.count + 1;
};
export const Counter = component$((props) => {
  const state = useStore({ count: 0 });
  return (
    <Fragment>
      <p>Counter: {state.count}</p>
      <button onClick$={(event) => state.incrementCount(event)}>+1</button>
    </Fragment>
  );
});
export default Counter;
