// packages/party/content/2-templating/3-loop/solid/Colors.jsx
import { For, createSignal } from "solid-js";

function Colors(props) {
  const [colors, setColors] = createSignal(["red", "green", "blue"]);
  return <ul>
      <For each={colors()}>
        {(color, _index) => {
        const index = _index();

        return <li>{color}</li>;
      }}
      </For>
    </ul>;
}

export default Colors;

// packages/party/content/2-templating/3-loop/qwik/Colors.jsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";
export const Colors = component$((props) => {
  const state = useStore({ colors: ["red", "green", "blue"] });
  return (
    <ul>
      {(state.colors || []).map(function (color) {
        return <li>{color}</li>;
      })}
    </ul>
  );
});
export default Colors;
