// packages/party/content/4-component-composition/3-slot/react/FunnyButton.tsx
import * as React from 'react';

export default function FunnyButton(props: any) {
  return (
    <button style="background: rgba(0, 0, 0, 0.4); color: #fff; padding: 10px 20px; font-size: 30px; border: 2px solid #fff; margin: 8px; transform: scale(0.9); box-shadow: 4px 4px rgba(0, 0, 0, 0.4); transition: transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s; outline: 0;">
      {props.children}
    </button>
  );
}

// packages/party/content/4-component-composition/3-slot/angular/FunnyButton.ts
import { Component } from "@angular/core";

@Component({
  selector: "funny-button, FunnyButton",
  template: `
    <button
      style="
        background: rgba(0, 0, 0, 0.4);
        color: #fff;
        padding: 10px 20px;
        font-size: 30px;
        border: 2px solid #fff;
        margin: 8px;
        transform: scale(0.9);
        box-shadow: 4px 4px rgba(0, 0, 0, 0.4);
        transition: transform 0.2s cubic-bezier(0.34, 1.65, 0.88, 0.925) 0s;
        outline: 0;
      "
    >
      <ng-content></ng-content>
    </button>
  `,
})
export default class FunnyButton {}
