// packages/party/content/2-templating/6-conditional/react/TrafficLight.tsx
import * as React from "react";
import { useState } from "react";

export default function TrafficLight(props: any) {
  const [TRAFFIC_LIGHTS, setTRAFFIC_LIGHTS] = useState(() => ["red", "green"]);

  const [lightIndex, setLightIndex] = useState(() => 0);

  function light() {
    return TRAFFIC_LIGHTS[lightIndex];
  }

  function toggleLight() {
    setLightIndex(lightIndex === 0 ? 1 : 0);
  }

  return (
    <>
      <button onClick={() => toggleLight}>Toggle light</button>
      <p>
        Light is:
        {light()}
      </p>
      <p>
        You must
        {light() === "red" ? <span>STOP</span> : <span>GO</span>}
      </p>
    </>
  );
}

// packages/party/sveltosis/2-templating/6-conditional/TrafficLight.svelte
<script lang="ts">
	const TRAFFIC_LIGHTS = ['red', 'green'];
	let lightIndex = 0;

	$: light = TRAFFIC_LIGHTS[lightIndex];

	function toggleLight() {
		lightIndex = lightIndex === 0 ? 1 : 0;
	}
</script>

<button on:click={toggleLight}>Toggle light</button>
<p>Light is: {light}</p>
<p>
	You must
	{#if light === 'red'}
		<span>STOP</span>
	{:else}
		<span>GO</span>
	{/if}
</p>
