// packages/party/content/2-templating/6-conditional/vue/TrafficLight.vue
<template>
  <button @click="toggleLight">Toggle light</button>
  <p>Light is: {{ light }}</p>
  <p>
    You must

    <template v-if="light === 'red'">
      <span>STOP</span>
    </template>

    <template v-else>
      <span>GO</span>
    </template>
  </p>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

const TRAFFIC_LIGHTS = ref(["red", "green"]);
const lightIndex = ref(0);

const light = computed(() => {
  return TRAFFIC_LIGHTS.value[lightIndex.value];
});

function toggleLight() {
  lightIndex.value = lightIndex.value === 0 ? 1 : 0;
}
</script>

// packages/party/sveltosis/2-templating/6-conditional/TrafficLight.svelte
<script lang="ts">
	const TRAFFIC_LIGHTS = ['red', 'green'];
	let lightIndex = 0;

	$: light = TRAFFIC_LIGHTS[lightIndex];

	function toggleLight() {
		lightIndex = lightIndex === 0 ? 1 : 0;
	}
</script>

<button on:click={toggleLight}>Toggle light</button>
<p>Light is: {light}</p>
<p>
	You must
	{#if light === 'red'}
		<span>STOP</span>
	{:else}
		<span>GO</span>
	{/if}
</p>
