// packages/party/content/5-form-input/1-input-text/angular/InputHello.ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { Component } from '@angular/core';

@Component({
  selector: 'input-hello, InputHello',
  template: `
    <ng-container>
      <p>{{ text }}</p>
      <input (input)="text = $event.target.value" [attr.value]="text" />
    </ng-container>
  `,
})
export class InputHello {
  text = 'Hello World';
}

@NgModule({
  declarations: [InputHello],
  imports: [BrowserModule],
  exports: [InputHello],
})
export class InputHelloModule {}

// packages/party/content/5-form-input/1-input-text/react/InputHello.tsx
import * as React from 'react';
import { useState } from 'react';

export default function InputHello(props: any) {
  const [text, setText] = useState(() => 'Hello World');

  return (
    <>
      <p>{text}</p>
      <input onChange={(event) => setText(event.target.value)} value={text} />
    </>
  );
}
