// packages/party/content/5-form-input/1-input-text/qwik/InputHello.jsx
import { Fragment, component$, h, useStore } from '@builder.io/qwik';
export const InputHello = component$((props) => {
  const state = useStore({ text: 'Hello World' });
  return (
    <Fragment>
      <p>{state.text}</p>
      <input onChange$={(event) => (state.text = event.target.value)} value={state.text}></input>
    </Fragment>
  );
});
export default InputHello;

// packages/party/content/5-form-input/1-input-text/react/InputHello.tsx
import * as React from 'react';
import { useState } from 'react';

export default function InputHello(props: any) {
  const [text, setText] = useState(() => 'Hello World');

  return (
    <>
      <p>{text}</p>
      <input onChange={(event) => setText(event.target.value)} value={text} />
    </>
  );
}
