// packages/party/content/4-component-composition/1-props/qwik/UserProfile.jsx
import { Fragment, component$, h } from "@builder.io/qwik";
export const UserProfile = component$((props) => {
  return (
    <Fragment>
      <p>My name is {props.name} !</p>
      <p>My age is {props.age} !</p>
      <p>My favourite colors are {props.favouriteColors.join(", ")} !</p>
      <p>I am {props.isAvailable ? "available" : "not available"}</p>
    </Fragment>
  );
});
export default UserProfile;

// packages/party/content/4-component-composition/1-props/solid/UserProfile.jsx
function UserProfile(props) {
  return <>
      <p>
        My name is
        {props.name}!
      </p>
      <p>
        My age is
        {props.age}!
      </p>
      <p>
        My favourite colors are
        {props.favouriteColors.join(", ")}!
      </p>
      <p>
        I am
        {props.isAvailable ? "available" : "not available"}
      </p>
    </>;
}
export default UserProfile;
