// packages/party/content/4-component-composition/1-props/vue/UserProfile.vue
<template>
  <p>My name is {{ name }} !</p>
  <p>My age is {{ age }} !</p>
  <p>My favourite colors are {{ favouriteColors.join(", ") }} !</p>
  <p>I am {{ isAvailable ? "available" : "not available" }}</p>
</template>

<script setup lang="ts">
const props = withDefaults(defineProps<undefined>(), {});
</script>

// packages/party/content/4-component-composition/1-props/solid/UserProfile.jsx
function UserProfile(props) {
  return <>
      <p>
        My name is
        {props.name}!
      </p>
      <p>
        My age is
        {props.age}!
      </p>
      <p>
        My favourite colors are
        {props.favouriteColors.join(", ")}!
      </p>
      <p>
        I am
        {props.isAvailable ? "available" : "not available"}
      </p>
    </>;
}
export default UserProfile;
