// packages/party/content/5-form-input/2-checkbox/vue/IsAvailable.vue
<template>
  <input
    id="is-available"
    type="checkbox"
    @input="isAvailable = $event.target.checked"
    :checked="isAvailable"
  />
  <label for="is-available">Is available</label>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const isAvailable = ref(false);
</script>

// packages/party/content/5-form-input/2-checkbox/angular/IsAvailable.ts
import { Component } from "@angular/core";

@Component({
  selector: "is-available, IsAvailable",
  template: `
    <div>
      <input
        id="is-available"
        type="checkbox"
        (input)="isAvailable = $event.target.checked"
        [checked]="isAvailable"
      />
      <label for="is-available">Is available</label>
    </div>
  `,
})
export default class IsAvailable {
  isAvailable = false;
}
