// packages/party/content/5-form-input/2-checkbox/react/IsAvailable.tsx
import * as React from 'react';
import { useState } from 'react';

export default function IsAvailable(props: any) {
  const [isAvailable, setIsAvailable] = useState(() => false);

  return (
    <>
      <input
        id="is-available"
        type="checkbox"
        onChange={(event) => setIsAvailable(event.target.checked)}
        checked={isAvailable}
      />
      <label for="is-available">Is available</label>
    </>
  );
}

// packages/party/content/5-form-input/2-checkbox/solid/IsAvailable.jsx
import { createSignal } from 'solid-js';
function IsAvailable(props) {
  const [isAvailable, setIsAvailable] = createSignal(false);
  return (
    <>
      <input
        id="is-available"
        type="checkbox"
        onInput={(event) => setIsAvailable(event.target.checked)}
        checked={isAvailable()}
      />
      <label for="is-available">Is available</label>
    </>
  );
}
export default IsAvailable;
