// packages/party/content/2-templating/2-styling/qwik/CssStyle.jsx
import { Fragment, component$, h, useStylesScoped$ } from '@builder.io/qwik';
export const CssStyle = component$((props) => {
  useStylesScoped$(STYLES);
  return (
    <Fragment>
      <h1 class="title">I am red</h1>
      <button style="font-size: 10rem;">I am a button</button>
    </Fragment>
  );
});
export default CssStyle;
export const STYLES = `

	.title {
		color: red;
	}
`;

// packages/party/content/2-templating/2-styling/react/CssStyle.tsx
import * as React from 'react';

export default function CssStyle(props: any) {
  return (
    <>
      <>
        <h1 className="title">I am red</h1>
        <button style="font-size: 10rem;">I am a button</button>
      </>
      <style jsx>{`
        .title {
          color: red;
        }
      `}</style>
    </>
  );
}
