// packages/party/content/2-templating/2-styling/angular/CssStyle.ts
import { Component } from "@angular/core";

@Component({
  selector: "css-style, CssStyle",
  template: `
    <div>
      <h1 class="title">I am red</h1>
      <button style="font-size: 10rem">I am a button</button>
    </div>
  `,
  styles: [
    `
      .title {
        color: red;
      }
    `,
  ],
})
export default class CssStyle {}

// packages/party/content/2-templating/2-styling/react/CssStyle.tsx
import * as React from 'react';

export default function CssStyle(props: any) {
  return (
    <>
      <>
        <h1 className="title">I am red</h1>
        <button style="font-size: 10rem;">I am a button</button>
      </>
      <style jsx>{`
        .title {
          color: red;
        }
      `}</style>
    </>
  );
}
