// packages/party/content/4-component-composition/5-actions/react/Actions.tsx
import * as React from 'react';
import { useState, useRef, useEffect } from 'react';

export default function Actions(props: any) {
  const button0 = useRef(null);
  const [buttonText, setButtonText] = useState(() => 'Click Me');

  function onClick(node, args) {
    console.log('Mounted', node);
    return {
      update() {
        console.log('Updated', args);
      },
      destroy() {
        console.log('Destroyed', node);
      },
    };
  }

  const [actionHandler0, setActionHandler0] = useState(() => null);

  useEffect(() => {
    if (button0.current) {
      setActionHandler0(onClick(button0.current, buttonText));
    }
  }, []);

  useEffect(() => {
    if (!button0.current && actionHandler0) {
      actionHandler0?.destroy();
      setActionHandler0(null);
    } else if (button0.current && !actionHandler0) {
      if (button0.current) {
        setActionHandler0(onClick(button0.current, buttonText));
      }
    }
  }, [button0.current]);
  useEffect(() => {
    actionHandler0?.update(buttonText);
  }, [buttonText]);

  return <button ref={button0}>{buttonText}</button>;
}

// packages/party/content/4-component-composition/5-actions-experimental/solid/Actions.jsx
import { onMount, on, createEffect, createSignal } from "solid-js";

function Actions(props) {
  const [buttonText, setButtonText] = createSignal("Click Me");
  const [actionHandler0, setActionHandler0] = createSignal(null);

  function onClick(node, args) {
    console.log("Mounted", node);
    return {
      update() {
        console.log("Updated", args);
      },

      destroy() {
        console.log("Destroyed", node);
      }

    };
  }

  let button0;
  onMount(() => {
    if (button0) {
      setActionHandler0(onClick(button0, buttonText()));
    }
  });

  function onUpdateFn_0() {
    if (!button0 && actionHandler0()) {
      actionHandler0()?.destroy();
      setActionHandler0(null);
    } else if (button0 && !actionHandler0()) {
      if (button0) {
        setActionHandler0(onClick(button0, buttonText()));
      }
    }
  }

  createEffect(on(() => [button0], onUpdateFn_0));

  function onUpdateFn_1() {
    actionHandler0()?.update(buttonText());
  }

  createEffect(on(() => [buttonText()], onUpdateFn_1));
  return <button ref={button0}>{buttonText()}</button>;
}

export default Actions;
