// packages/party/content/3-lifecycle/1-on-mount/react/PageTitle.tsx
import * as React from "react";
import { useState, useEffect } from "react";

export default function PageTitle(props: any) {
  const [pageTitle, setPageTitle] = useState(() => "");

  useEffect(() => {
    setPageTitle(document.title);
  }, []);

  return (
    <p>
      Page title is:
      {pageTitle}
    </p>
  );
}

// packages/party/content/3-lifecycle/1-on-mount/qwik/PageTitle.jsx
import {
  Fragment,
  component$,
  h,
  useClientEffect$,
  useStore,
} from "@builder.io/qwik";
export const PageTitle = component$((props) => {
  const state = useStore({ pageTitle: "" });
  useClientEffect$(() => {
    state.pageTitle = document.title;
  });
  return <p>Page title is: {state.pageTitle}</p>;
});
export default PageTitle;
