// packages/party/content/5-form-input/3-radio/vue/PickPill.vue
<template>
  <div>Picked: {{ picked }}</div>
  <input
    id="blue-pill"
    type="radio"
    value="blue"
    :checked="picked === 'blue'"
    @input="picked = $event.target.value"
  />
  <label for="blue-pill">Blue pill</label>
  <input
    id="red-pill"
    type="radio"
    value="red"
    :checked="picked === 'red'"
    @input="picked = $event.target.value"
  />
  <label for="red-pill">Red pill</label>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const picked = ref('red');
</script>

// packages/party/content/5-form-input/3-radio/react/PickPill.tsx
import * as React from 'react';
import { useState } from 'react';

export default function PickPill(props: any) {
  const [picked, setPicked] = useState(() => 'red');

  return (
    <>
      <div>
        Picked:
        {picked}
      </div>
      <input
        id="blue-pill"
        type="radio"
        value="blue"
        checked={picked === 'blue'}
        onChange={(event) => setPicked(event.target.value)}
      />
      <label for="blue-pill">Blue pill</label>
      <input
        id="red-pill"
        type="radio"
        value="red"
        checked={picked === 'red'}
        onChange={(event) => setPicked(event.target.value)}
      />
      <label for="red-pill">Red pill</label>
    </>
  );
}
