// packages/party/content/4-component-composition/2-emit-to-parent/react/AnswerButton.tsx
import * as React from "react";

export default function AnswerButton(props: any) {
  function clickYes() {
    props.onYes();
  }

  function clickNo() {
    props.onNo();
  }

  return (
    <>
      <button onClick={() => clickYes}> YES </button>
      <button onClick={() => clickNo}> NO </button>
    </>
  );
}

// packages/party/content/4-component-composition/2-emit-to-parent/angular/AnswerButton.ts
import { Output, EventEmitter, Component } from "@angular/core";

@Component({
  selector: "answer-button, AnswerButton",
  template: `
    <div>
      <button (click)="clickYes">YES</button>
      <button (click)="clickNo">NO</button>
    </div>
  `,
})
export default class AnswerButton {
  @Output() onYes = new EventEmitter();
  @Output() onNo = new EventEmitter();

  clickYes = function clickYes() {
    this.onYes.emit();
  };
  clickNo = function clickNo() {
    this.onNo.emit();
  };
}
