// packages/party/content/5-form-input/4-select/react/ColorSelect.tsx
import * as React from 'react';
import { useState } from 'react';

export default function ColorSelect(props: any) {
  const [selectedColorId, setSelectedColorId] = useState(() => 2);

  const [colors, setColors] = useState(() => [
    {
      id: 1,
      text: 'red',
    },
    {
      id: 2,
      text: 'blue',
    },
    {
      id: 3,
      text: 'green',
    },
    {
      id: 4,
      text: 'gray',
      isDisabled: true,
    },
  ]);

  return (
    <select onChange={(event) => setSelectedColorId(event.target.value)} value={selectedColorId}>
      {colors?.map((color) => (
        <option value={color.id} disabled={color.isDisabled}>
          {color.text}
        </option>
      ))}
    </select>
  );
}

// packages/party/content/5-form-input/4-select/qwik/ColorSelect.jsx
import { Fragment, component$, h, useStore } from '@builder.io/qwik';
export const ColorSelect = component$((props) => {
  const state = useStore({
    colors: [
      { id: 1, text: 'red' },
      { id: 2, text: 'blue' },
      { id: 3, text: 'green' },
      { id: 4, text: 'gray', isDisabled: true },
    ],
    selectedColorId: 2,
  });
  return (
    <select
      onChange$={(event) => (state.selectedColorId = event.target.value)}
      value={state.selectedColorId}
    >
      {(state.colors || []).map(function (color) {
        return (
          <option value={color.id} disabled={color.isDisabled}>
            {color.text}
          </option>
        );
      })}
    </select>
  );
});
export default ColorSelect;
