// packages/party/content/2-templating/4-event-click/react/Counter.tsx
import * as React from 'react';
import { useState } from 'react';

export default function Counter(props: any) {
  const [count, setCount] = useState(() => 0);

  function incrementCount() {
    setCount(count + 1);
  }

  return (
    <>
      <p>
        Counter:
        {count}
      </p>
      <button onClick={(event) => incrementCount(event)}>+1</button>
    </>
  );
}

// packages/party/content/2-templating/4-event-click/solid/Counter.jsx
import { createSignal } from 'solid-js';
function Counter(props) {
  const [count, setCount] = createSignal(0);
  function incrementCount() {
    setCount(count() + 1);
  }
  return (
    <>
      <p>
        Counter:
        {count()}
      </p>
      <button onClick={(event) => incrementCount}>+1</button>
    </>
  );
}
export default Counter;
