// packages/party/content/2-templating/8-class-directive/angular/ClassDirective.ts
import { Component, Input } from '@angular/core';

const defaultProps = {};

@Component({
  selector: 'class-directive, ClassDirective',
  template: `
    <input [class]="\`form-input \${disabled ? 'disabled' : ''} \${focus ? 'focus' : ''}\`" />
  `,
})
export default class ClassDirective {
  @Input() disabled: any;

  focus = true;
}

// packages/party/content/2-templating/8-class-directive/react/ClassDirective.tsx
import * as React from 'react';
import { useState } from 'react';

export default function ClassDirective(props: any) {
  const [focus, setFocus] = useState(() => true);

  return (
    <input className={`form-input ${props.disabled ? 'disabled' : ''} ${focus ? 'focus' : ''}`} />
  );
}

ClassDirective.defaultProps = {};
