// packages/party/content/2-templating/8-class-directive/qwik/ClassDirective.jsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";
export const ClassDirective = component$((props) => {
  const state = useStore({ focus: true });
  return (
    <input
      class={`form-input ${props.disabled ? "props.disabled" : ""} ${
        state.focus ? "state.focus" : ""
      }`}
    ></input>
  );
});
export default ClassDirective;

// packages/party/content/2-templating/8-class-directive/react/ClassDirective.tsx
import * as React from 'react';
import { useState } from 'react';

export default function ClassDirective(props: any) {
  const [focus, setFocus] = useState(() => true);

  return (
    <input className={`form-input ${props.disabled ? 'disabled' : ''} ${focus ? 'focus' : ''}`} />
  );
}

ClassDirective.defaultProps = {};
