// packages/party/content/4-component-composition/2-emit-to-parent/react/App.tsx
import * as React from 'react';
import { useState } from 'react';
import AnswerButton from './AnswerButton.jsx';

export default function App(props: any) {
  const [canCome, setCanCome] = useState(() => true);

  function onAnswerNo() {
    setCanCome(false);
  }

  function onAnswerYes() {
    setCanCome(true);
  }

  return (
    <>
      <p>Can I come ?</p>
      <AnswerButton onYes={(event) => onAnswerYes(event)} onNo={(event) => onAnswerNo(event)} />
      <p style="font-size: 50px;">{canCome ? '😀' : '😥'}</p>
    </>
  );
}

// packages/party/content/4-component-composition/2-emit-to-parent/solid/App.jsx
import { createSignal } from 'solid-js';
import AnswerButton from './AnswerButton.jsx';
function App(props) {
  const [canCome, setCanCome] = createSignal(true);
  function onAnswerNo() {
    setCanCome(false);
  }
  function onAnswerYes() {
    setCanCome(true);
  }
  return (
    <>
      <p>Can I come ?</p>
      <AnswerButton onYes={(event) => onAnswerYes} onNo={(event) => onAnswerNo}></AnswerButton>
      <p style="font-size: 50px;">{canCome() ? '😀' : '😥'}</p>
    </>
  );
}
export default App;
