// packages/party/content/5-form-input/3-radio/vue/PickPill.vue
<template>
  <div>Picked: {{ picked }}</div>
  <input
    id="blue-pill"
    type="radio"
    value="blue"
    :checked="picked === 'blue'"
    @input="picked = $event.target.value"
  />
  <label for="blue-pill">Blue pill</label>
  <input
    id="red-pill"
    type="radio"
    value="red"
    :checked="picked === 'red'"
    @input="picked = $event.target.value"
  />
  <label for="red-pill">Red pill</label>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const picked = ref('red');
</script>

// packages/party/content/5-form-input/3-radio/angular/PickPill.ts
import { Component } from "@angular/core";

@Component({
  selector: "pick-pill, PickPill",
  template: `
    <div>
      <div>Picked: {{picked}}</div>
      <input
        id="blue-pill"
        type="radio"
        value="blue"
        [checked]="picked === 'blue'"
        (input)="picked = $event.target.value"
      />
      <label for="blue-pill">Blue pill</label>
      <input
        id="red-pill"
        type="radio"
        value="red"
        [checked]="picked === 'red'"
        (input)="picked = $event.target.value"
      />
      <label for="red-pill">Red pill</label>
    </div>
  `,
})
export default class PickPill {
  picked = "red";
}
