// packages/party/content/4-component-composition/4-context/solid/Context.jsx
import { useContext, createSignal } from 'solid-js';
import { Dynamic } from 'solid-js/web';
function Context(props) {
  const [activeTab, setActiveTab] = createSignal(0);
  const disabled = useContext('disabled');
  return (
    <Dynamic component={'activeTab'.Provider}>
      <div>
        Is disabled?
        {disabled}
      </div>
    </Dynamic>
  );
}
export default Context;

// packages/party/content/4-component-composition/4-context/react/Context.tsx
import * as React from 'react';
import { useState, useContext } from 'react';

export default function Context(props: any) {
  const [activeTab, setActiveTab] = useState(() => 0);

  const disabled = useContext('disabled');

  return (
    <Context.Provider value={activeTab}>
      <div>
        Is disabled?
        {disabled}
      </div>
    </Context.Provider>
  );
}
