// packages/party/content/5-form-input/2-checkbox/vue/IsAvailable.vue
<template>
  <input
    id="is-available"
    type="checkbox"
    @input="isAvailable = $event.target.checked"
    :checked="isAvailable"
  />
  <label for="is-available">Is available</label>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const isAvailable = ref(false);
</script>

// packages/party/content/5-form-input/2-checkbox/react/IsAvailable.tsx
import * as React from 'react';
import { useState } from 'react';

export default function IsAvailable(props: any) {
  const [isAvailable, setIsAvailable] = useState(() => false);

  return (
    <>
      <input
        id="is-available"
        type="checkbox"
        onChange={(event) => setIsAvailable(event.target.checked)}
        checked={isAvailable}
      />
      <label for="is-available">Is available</label>
    </>
  );
}
